wallpaper {
    monitor =
    path = ~/Downloads/wallpapers/valley-of-the-yosemite.jpg
    #path = ~/Downloads/wallpapers/on-the-coast-of-new-jersey.jpg
    #path = ~/Downloads/wallpapers/tomas-shore.jpg
    #path = ~/Downloads/wallpapers/inner-lagoon-thought-cloud.jpg
    #path = ~/Downloads/wallpapers/comtemplar.jpg
    #path = ~/Downloads/wallpapers/light-outside-inside.jpg
    #path = ~/Downloads/wallpapers/orilla.jpg
    #path = ~/Downloads/wallpapers/tomas-4k.png
    #path = ~/Downloads/wallpapers/warm-texture.jpg
    #path = ~/Downloads/wallpapers/warm-2.jpg
    #path = ~/Downloads/wallpapers/tomas-4k.png
    #path = ~/Downloads/wallpapers/warm-3.jpg
    #path = ~/Downloads/wallpapers/warm-4.jpg
    fit_mode = cover
}

splash = false 
