wallpaper {
    monitor =
    #path = ~/Downloads/tomas-4k.png
    path = ~/Downloads/warm-texture.jpg
    #path = ~/Downloads/warm-2.jpg
    #path = ~/Downloads/warm-3.jpg
    #path = ~/Downloads/warm-4.jpg
    fit_mode = cover
}

splash = false 
