wallpaper {
    monitor =
    path = ~/Downloads/valley-of-the-yosemite.jpg
    #path = ~/Downloads/on-the-coast-of-new-jersey.jpg
    #path = ~/Downloads/tomas-shore.jpg
    #path = ~/Downloads/inner-lagoon-thought-cloud.jpg
    #path = ~/Downloads/comtemplar.jpg
    #path = ~/Downloads/light-outside-inside.jpg
    #path = ~/Downloads/orilla.jpg
    #path = ~/Downloads/tomas-4k.png
    #path = ~/Downloads/warm-texture.jpg
    #path = ~/Downloads/warm-2.jpg
    #path = ~/Downloads/tomas-4k.png
    #path = ~/Downloads/warm-3.jpg
    #path = ~/Downloads/warm-4.jpg
    fit_mode = cover
}

splash = false 
